#!/usr/bin/env python3

import zlib
import base64

# ストリームを取り出して文字列に
ascii85_data = 'GarW2YmLOu$q1!kMCDOn-e[>.$X25>BnYkA%tmmRrsRk\=,6t`AhnX"^_ds]e,sL,E[q]T?Q`oWi&ba;4d(2]6:3VgG(^jPB:%UQ7[+b&%uu[?2s&XeG[OH!]UrC\[@;s!VV-3(bHtC&)R>O1_C>BiTDcTJ4L1+GD8a\'`(o.rP+"p+~>'

# ASCII85 decode
binary_data = base64.a85decode(ascii85_data, adobe=True)

# Flate (zlib) decode
decoded = zlib.decompress(binary_data)

print(decoded.decode('utf-8', errors='replace'))
